/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallingPage: typeof import('./src/components/CallingPage.vue')['default']
    FileManager: typeof import('./src/components/FileManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/SearchDialog.vue')['default']
    SimpleChat: typeof import('./src/components/SimpleChat.vue')['default']
  }
}
