spring:
  application:
    name: demo
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-v4-flash
          temperature: 0.8

      base-url: https://api.deepseek.com

    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:0.8b
      embedding:
        model: nomic-embed-text
    vectorstore:
      milvus:
        client:
          port: 19530
          host: "localhost"
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 768
        indexType: IVF_FLAT
        metricType: COSINE
        initializeSchema: true
  data:
    redis:
      host: localhost
      port: 6379            # 端口号
      password:             # 密码（无密码则留空）
      database: 0           # 选择数据库索引
      lettuce:
        pool:
          max-active: 8     # 最大连接数
          max-idle: 8       # 最大空闲连接数
          min-idle: 2       # 最小空闲连接数

server:
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

kind: Application





